package com.cobip.domain.activity;

public enum ActivityType {
    TEMPLATE_CREATED,
    TEMPLATE_UPDATED,
    TEMPLATE_DELETED,
    TEMPLATE_FAVORITED,
    TEMPLATE_UNFAVORITED,
    TEMPLATE_FILE_UPLOADED,
    TEMPLATE_THUMBNAIL_UPLOADED,
    CERTIFICATE_ISSUED
}
